# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20170724_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_logo',
            field=models.CharField(default='idk', max_length=100),
            preserve_default=False,
        ),
    ]
