# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_folder_folder_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
